before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: Vw7hMaKzzp5q7vzrgQJZv12YiTjFluG0J5rk0Sj0Gh8d4e7kReIVFRQ4GQl63sGeIKwp2iIcM3wYaypGO2B32G08Zs04vLUaYwLql4s/jdnF+XC99QyhK/I4X42OJkjQ9AWip18umAySll3E820pQHpz6c/5pgB6PUQTpL36eDzngUsCyGFsmEBq2NMjH9kudbGS3gwbb/3ai4bb7N0t0hc8OQ6XyNdOxoCY9bLLdhA3CwBNN6y13iwIkYwd2n5/b6ExEr3CX+iXIncsygura6DlR6zkZlOXUfTrmz0qixkBJPR/bvgfzoxUb6muvb0wQAs3DMITs8ytb74VvxsFWG3L5H7VguS/z/A4onQBOc/GKcYsHpqpXVySsz5DwWywRt1bgBstSvoLG0cFXvBXoMdOYikT6j5vCd/+zZnw7DL8Y8Ogw2S5s90tkBXB3qFTHaS2P63+MMDSdjxr6uurhollbbf/4Ea0EettpYTvmRnfJ0fezMSsykjFwjiQq/2GtjqfTmrCWgnR2OnK87nRRRCDilJyLK/gnufeM9GGVU2K130bEwzcAsl8r02gTbGPjVytHo4I0VdrsEUXewdWMEbzxtlhch+JlaZUArrmc1EsgwR8OtXilusqbrDMbv32NsbNlOUjcrWNhabw3bd9hfW0DZdFkzmNkg64U9QSwzc= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml
    # - CRYPTO_AES_ENCRYPTED_SH: YjZiMmIwNjYyY2E0OGI5YjQ4ZmI3YTdkYmU4NjViN2I=I93wn43H8K4/eB5Wvi6A2irUFGh17rfCMer38OP/nGwK/4CqVaqXLLQlnG0aW/B+Zt+rUVfwxFxQplOTNqrK3WtMKw1307LZjVv/TPshn/uGxPUqpJTI075x+/b73WEYCXFvwCMwE1GVNiZTS8hGRmmhdLsFy7jlqQwGm0sp7VhUDRSmPsSH5rPplwKCvisqfcMBfCiGjfpXmrbX3gAnwDorfdHLKPFJlzUTcxPeEAjhT8pDckamS+V5scyCZwCqQdRFGOGva3KDyjBIOISbKkdhk1Yn8PczsJe7zrT+j2+mbBV32HPOQdmrwfPC/u3uLZSeTa+kob416KrOdHZWzk1p8DitQBgZUDwBd3ZVvxwc1lOrpciCunR3HXuaJIXKEkrzDu0V2uV/0V9vkeKFmFrTTnKad/4HPtB3GEfBkDPWEWOoYglEeIhMv5cBWdYnfFaV5Kkp145NI8IBQovJ07UyMk7uPcUEcY+V4s3RP3JZ2ZkfSOBXSMT5oa6m6DOX+w3ZNMsj4S0DYt/ncKvOOtqNOiXCChFGgwVd3hgfifgpiWF9CyqDL9AUkRgJyE9uFWccdPID8hw9hvHm1CinboH0CQZkX0/RbIy/R0S8nVS22HTX0SOgq6/yhacalRn6pkX1KxWgZc8gmgTlGvX/YcEzB31sQhy//jm69dd+XELcijk+jFmdf9jnW9Lyo366sRXXdnqFE5gDE4ZMOvyDyURDtKyBnaoy4FnMJY0HAfAIY46MN2/9ZKb9FQTigvVV # CRYPTO_AES_ENCRYPTED_SH
language:
    - node_js
node_js:
    # - 6
    - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
